export type { App } from "@wingmnn/api";
export type {
	AutoHandleAction,
	AutoHandledItem,
	BriefingStat,
	EmailCategory,
	EmailProvider,
	MailModuleData,
	SerializedAccount,
	SerializedAttachment,
	SerializedAttachmentWithContext,
	SerializedEmail,
	SerializedEmailDetail,
	SerializedThread,
	SerializedThreadDetail,
	SyncStatus,
	TriageAction,
	TriageActionButton,
	TriageItem,
	TriageStatus,
} from "./mail";
