/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as AuthenticatedOnboardingRouteImport } from './routes/_authenticated/onboarding'
import { Route as AuthenticatedAppRouteImport } from './routes/_authenticated/_app'
import { Route as AuthenticatedOnboardingIndexRouteImport } from './routes/_authenticated/onboarding/index'
import { Route as AuthenticatedAppIndexRouteImport } from './routes/_authenticated/_app/index'
import { Route as AuthenticatedOnboardingStep4RouteImport } from './routes/_authenticated/onboarding/step4'
import { Route as AuthenticatedOnboardingStep3RouteImport } from './routes/_authenticated/onboarding/step3'
import { Route as AuthenticatedOnboardingStep2RouteImport } from './routes/_authenticated/onboarding/step2'
import { Route as AuthenticatedOnboardingStep1RouteImport } from './routes/_authenticated/onboarding/step1'
import { Route as AuthenticatedOnboardingLaunchRouteImport } from './routes/_authenticated/onboarding/launch'
import { Route as AuthenticatedAppProfileRouteImport } from './routes/_authenticated/_app/profile'
import { Route as AuthenticatedAppModuleTravelRouteImport } from './routes/_authenticated/_app/module/travel'
import { Route as AuthenticatedAppModuleTaskRouteImport } from './routes/_authenticated/_app/module/task'
import { Route as AuthenticatedAppModuleSocialRouteImport } from './routes/_authenticated/_app/module/social'
import { Route as AuthenticatedAppModuleNotesRouteImport } from './routes/_authenticated/_app/module/notes'
import { Route as AuthenticatedAppModuleMailRouteImport } from './routes/_authenticated/_app/module/mail'
import { Route as AuthenticatedAppModuleHealthRouteImport } from './routes/_authenticated/_app/module/health'
import { Route as AuthenticatedAppModuleFinRouteImport } from './routes/_authenticated/_app/module/fin'
import { Route as AuthenticatedAppModuleFilesRouteImport } from './routes/_authenticated/_app/module/files'
import { Route as AuthenticatedAppModuleCrmRouteImport } from './routes/_authenticated/_app/module/crm'
import { Route as AuthenticatedAppModuleCalRouteImport } from './routes/_authenticated/_app/module/cal'

const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedOnboardingRoute = AuthenticatedOnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedAppRoute = AuthenticatedAppRouteImport.update({
  id: '/_app',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedOnboardingIndexRoute =
  AuthenticatedOnboardingIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedOnboardingRoute,
  } as any)
const AuthenticatedAppIndexRoute = AuthenticatedAppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedAppRoute,
} as any)
const AuthenticatedOnboardingStep4Route =
  AuthenticatedOnboardingStep4RouteImport.update({
    id: '/step4',
    path: '/step4',
    getParentRoute: () => AuthenticatedOnboardingRoute,
  } as any)
const AuthenticatedOnboardingStep3Route =
  AuthenticatedOnboardingStep3RouteImport.update({
    id: '/step3',
    path: '/step3',
    getParentRoute: () => AuthenticatedOnboardingRoute,
  } as any)
const AuthenticatedOnboardingStep2Route =
  AuthenticatedOnboardingStep2RouteImport.update({
    id: '/step2',
    path: '/step2',
    getParentRoute: () => AuthenticatedOnboardingRoute,
  } as any)
const AuthenticatedOnboardingStep1Route =
  AuthenticatedOnboardingStep1RouteImport.update({
    id: '/step1',
    path: '/step1',
    getParentRoute: () => AuthenticatedOnboardingRoute,
  } as any)
const AuthenticatedOnboardingLaunchRoute =
  AuthenticatedOnboardingLaunchRouteImport.update({
    id: '/launch',
    path: '/launch',
    getParentRoute: () => AuthenticatedOnboardingRoute,
  } as any)
const AuthenticatedAppProfileRoute = AuthenticatedAppProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AuthenticatedAppRoute,
} as any)
const AuthenticatedAppModuleTravelRoute =
  AuthenticatedAppModuleTravelRouteImport.update({
    id: '/module/travel',
    path: '/module/travel',
    getParentRoute: () => AuthenticatedAppRoute,
  } as any)
const AuthenticatedAppModuleTaskRoute =
  AuthenticatedAppModuleTaskRouteImport.update({
    id: '/module/task',
    path: '/module/task',
    getParentRoute: () => AuthenticatedAppRoute,
  } as any)
const AuthenticatedAppModuleSocialRoute =
  AuthenticatedAppModuleSocialRouteImport.update({
    id: '/module/social',
    path: '/module/social',
    getParentRoute: () => AuthenticatedAppRoute,
  } as any)
const AuthenticatedAppModuleNotesRoute =
  AuthenticatedAppModuleNotesRouteImport.update({
    id: '/module/notes',
    path: '/module/notes',
    getParentRoute: () => AuthenticatedAppRoute,
  } as any)
const AuthenticatedAppModuleMailRoute =
  AuthenticatedAppModuleMailRouteImport.update({
    id: '/module/mail',
    path: '/module/mail',
    getParentRoute: () => AuthenticatedAppRoute,
  } as any)
const AuthenticatedAppModuleHealthRoute =
  AuthenticatedAppModuleHealthRouteImport.update({
    id: '/module/health',
    path: '/module/health',
    getParentRoute: () => AuthenticatedAppRoute,
  } as any)
const AuthenticatedAppModuleFinRoute =
  AuthenticatedAppModuleFinRouteImport.update({
    id: '/module/fin',
    path: '/module/fin',
    getParentRoute: () => AuthenticatedAppRoute,
  } as any)
const AuthenticatedAppModuleFilesRoute =
  AuthenticatedAppModuleFilesRouteImport.update({
    id: '/module/files',
    path: '/module/files',
    getParentRoute: () => AuthenticatedAppRoute,
  } as any)
const AuthenticatedAppModuleCrmRoute =
  AuthenticatedAppModuleCrmRouteImport.update({
    id: '/module/crm',
    path: '/module/crm',
    getParentRoute: () => AuthenticatedAppRoute,
  } as any)
const AuthenticatedAppModuleCalRoute =
  AuthenticatedAppModuleCalRouteImport.update({
    id: '/module/cal',
    path: '/module/cal',
    getParentRoute: () => AuthenticatedAppRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof AuthenticatedAppIndexRoute
  '/auth': typeof AuthRoute
  '/onboarding': typeof AuthenticatedOnboardingRouteWithChildren
  '/profile': typeof AuthenticatedAppProfileRoute
  '/onboarding/launch': typeof AuthenticatedOnboardingLaunchRoute
  '/onboarding/step1': typeof AuthenticatedOnboardingStep1Route
  '/onboarding/step2': typeof AuthenticatedOnboardingStep2Route
  '/onboarding/step3': typeof AuthenticatedOnboardingStep3Route
  '/onboarding/step4': typeof AuthenticatedOnboardingStep4Route
  '/onboarding/': typeof AuthenticatedOnboardingIndexRoute
  '/module/cal': typeof AuthenticatedAppModuleCalRoute
  '/module/crm': typeof AuthenticatedAppModuleCrmRoute
  '/module/files': typeof AuthenticatedAppModuleFilesRoute
  '/module/fin': typeof AuthenticatedAppModuleFinRoute
  '/module/health': typeof AuthenticatedAppModuleHealthRoute
  '/module/mail': typeof AuthenticatedAppModuleMailRoute
  '/module/notes': typeof AuthenticatedAppModuleNotesRoute
  '/module/social': typeof AuthenticatedAppModuleSocialRoute
  '/module/task': typeof AuthenticatedAppModuleTaskRoute
  '/module/travel': typeof AuthenticatedAppModuleTravelRoute
}
export interface FileRoutesByTo {
  '/': typeof AuthenticatedAppIndexRoute
  '/auth': typeof AuthRoute
  '/profile': typeof AuthenticatedAppProfileRoute
  '/onboarding/launch': typeof AuthenticatedOnboardingLaunchRoute
  '/onboarding/step1': typeof AuthenticatedOnboardingStep1Route
  '/onboarding/step2': typeof AuthenticatedOnboardingStep2Route
  '/onboarding/step3': typeof AuthenticatedOnboardingStep3Route
  '/onboarding/step4': typeof AuthenticatedOnboardingStep4Route
  '/onboarding': typeof AuthenticatedOnboardingIndexRoute
  '/module/cal': typeof AuthenticatedAppModuleCalRoute
  '/module/crm': typeof AuthenticatedAppModuleCrmRoute
  '/module/files': typeof AuthenticatedAppModuleFilesRoute
  '/module/fin': typeof AuthenticatedAppModuleFinRoute
  '/module/health': typeof AuthenticatedAppModuleHealthRoute
  '/module/mail': typeof AuthenticatedAppModuleMailRoute
  '/module/notes': typeof AuthenticatedAppModuleNotesRoute
  '/module/social': typeof AuthenticatedAppModuleSocialRoute
  '/module/task': typeof AuthenticatedAppModuleTaskRoute
  '/module/travel': typeof AuthenticatedAppModuleTravelRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/auth': typeof AuthRoute
  '/_authenticated/_app': typeof AuthenticatedAppRouteWithChildren
  '/_authenticated/onboarding': typeof AuthenticatedOnboardingRouteWithChildren
  '/_authenticated/_app/profile': typeof AuthenticatedAppProfileRoute
  '/_authenticated/onboarding/launch': typeof AuthenticatedOnboardingLaunchRoute
  '/_authenticated/onboarding/step1': typeof AuthenticatedOnboardingStep1Route
  '/_authenticated/onboarding/step2': typeof AuthenticatedOnboardingStep2Route
  '/_authenticated/onboarding/step3': typeof AuthenticatedOnboardingStep3Route
  '/_authenticated/onboarding/step4': typeof AuthenticatedOnboardingStep4Route
  '/_authenticated/_app/': typeof AuthenticatedAppIndexRoute
  '/_authenticated/onboarding/': typeof AuthenticatedOnboardingIndexRoute
  '/_authenticated/_app/module/cal': typeof AuthenticatedAppModuleCalRoute
  '/_authenticated/_app/module/crm': typeof AuthenticatedAppModuleCrmRoute
  '/_authenticated/_app/module/files': typeof AuthenticatedAppModuleFilesRoute
  '/_authenticated/_app/module/fin': typeof AuthenticatedAppModuleFinRoute
  '/_authenticated/_app/module/health': typeof AuthenticatedAppModuleHealthRoute
  '/_authenticated/_app/module/mail': typeof AuthenticatedAppModuleMailRoute
  '/_authenticated/_app/module/notes': typeof AuthenticatedAppModuleNotesRoute
  '/_authenticated/_app/module/social': typeof AuthenticatedAppModuleSocialRoute
  '/_authenticated/_app/module/task': typeof AuthenticatedAppModuleTaskRoute
  '/_authenticated/_app/module/travel': typeof AuthenticatedAppModuleTravelRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/onboarding'
    | '/profile'
    | '/onboarding/launch'
    | '/onboarding/step1'
    | '/onboarding/step2'
    | '/onboarding/step3'
    | '/onboarding/step4'
    | '/onboarding/'
    | '/module/cal'
    | '/module/crm'
    | '/module/files'
    | '/module/fin'
    | '/module/health'
    | '/module/mail'
    | '/module/notes'
    | '/module/social'
    | '/module/task'
    | '/module/travel'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/profile'
    | '/onboarding/launch'
    | '/onboarding/step1'
    | '/onboarding/step2'
    | '/onboarding/step3'
    | '/onboarding/step4'
    | '/onboarding'
    | '/module/cal'
    | '/module/crm'
    | '/module/files'
    | '/module/fin'
    | '/module/health'
    | '/module/mail'
    | '/module/notes'
    | '/module/social'
    | '/module/task'
    | '/module/travel'
  id:
    | '__root__'
    | '/_authenticated'
    | '/auth'
    | '/_authenticated/_app'
    | '/_authenticated/onboarding'
    | '/_authenticated/_app/profile'
    | '/_authenticated/onboarding/launch'
    | '/_authenticated/onboarding/step1'
    | '/_authenticated/onboarding/step2'
    | '/_authenticated/onboarding/step3'
    | '/_authenticated/onboarding/step4'
    | '/_authenticated/_app/'
    | '/_authenticated/onboarding/'
    | '/_authenticated/_app/module/cal'
    | '/_authenticated/_app/module/crm'
    | '/_authenticated/_app/module/files'
    | '/_authenticated/_app/module/fin'
    | '/_authenticated/_app/module/health'
    | '/_authenticated/_app/module/mail'
    | '/_authenticated/_app/module/notes'
    | '/_authenticated/_app/module/social'
    | '/_authenticated/_app/module/task'
    | '/_authenticated/_app/module/travel'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  AuthRoute: typeof AuthRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/onboarding': {
      id: '/_authenticated/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof AuthenticatedOnboardingRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/_app': {
      id: '/_authenticated/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedAppRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/onboarding/': {
      id: '/_authenticated/onboarding/'
      path: '/'
      fullPath: '/onboarding/'
      preLoaderRoute: typeof AuthenticatedOnboardingIndexRouteImport
      parentRoute: typeof AuthenticatedOnboardingRoute
    }
    '/_authenticated/_app/': {
      id: '/_authenticated/_app/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedAppIndexRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/onboarding/step4': {
      id: '/_authenticated/onboarding/step4'
      path: '/step4'
      fullPath: '/onboarding/step4'
      preLoaderRoute: typeof AuthenticatedOnboardingStep4RouteImport
      parentRoute: typeof AuthenticatedOnboardingRoute
    }
    '/_authenticated/onboarding/step3': {
      id: '/_authenticated/onboarding/step3'
      path: '/step3'
      fullPath: '/onboarding/step3'
      preLoaderRoute: typeof AuthenticatedOnboardingStep3RouteImport
      parentRoute: typeof AuthenticatedOnboardingRoute
    }
    '/_authenticated/onboarding/step2': {
      id: '/_authenticated/onboarding/step2'
      path: '/step2'
      fullPath: '/onboarding/step2'
      preLoaderRoute: typeof AuthenticatedOnboardingStep2RouteImport
      parentRoute: typeof AuthenticatedOnboardingRoute
    }
    '/_authenticated/onboarding/step1': {
      id: '/_authenticated/onboarding/step1'
      path: '/step1'
      fullPath: '/onboarding/step1'
      preLoaderRoute: typeof AuthenticatedOnboardingStep1RouteImport
      parentRoute: typeof AuthenticatedOnboardingRoute
    }
    '/_authenticated/onboarding/launch': {
      id: '/_authenticated/onboarding/launch'
      path: '/launch'
      fullPath: '/onboarding/launch'
      preLoaderRoute: typeof AuthenticatedOnboardingLaunchRouteImport
      parentRoute: typeof AuthenticatedOnboardingRoute
    }
    '/_authenticated/_app/profile': {
      id: '/_authenticated/_app/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof AuthenticatedAppProfileRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/_app/module/travel': {
      id: '/_authenticated/_app/module/travel'
      path: '/module/travel'
      fullPath: '/module/travel'
      preLoaderRoute: typeof AuthenticatedAppModuleTravelRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/_app/module/task': {
      id: '/_authenticated/_app/module/task'
      path: '/module/task'
      fullPath: '/module/task'
      preLoaderRoute: typeof AuthenticatedAppModuleTaskRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/_app/module/social': {
      id: '/_authenticated/_app/module/social'
      path: '/module/social'
      fullPath: '/module/social'
      preLoaderRoute: typeof AuthenticatedAppModuleSocialRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/_app/module/notes': {
      id: '/_authenticated/_app/module/notes'
      path: '/module/notes'
      fullPath: '/module/notes'
      preLoaderRoute: typeof AuthenticatedAppModuleNotesRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/_app/module/mail': {
      id: '/_authenticated/_app/module/mail'
      path: '/module/mail'
      fullPath: '/module/mail'
      preLoaderRoute: typeof AuthenticatedAppModuleMailRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/_app/module/health': {
      id: '/_authenticated/_app/module/health'
      path: '/module/health'
      fullPath: '/module/health'
      preLoaderRoute: typeof AuthenticatedAppModuleHealthRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/_app/module/fin': {
      id: '/_authenticated/_app/module/fin'
      path: '/module/fin'
      fullPath: '/module/fin'
      preLoaderRoute: typeof AuthenticatedAppModuleFinRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/_app/module/files': {
      id: '/_authenticated/_app/module/files'
      path: '/module/files'
      fullPath: '/module/files'
      preLoaderRoute: typeof AuthenticatedAppModuleFilesRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/_app/module/crm': {
      id: '/_authenticated/_app/module/crm'
      path: '/module/crm'
      fullPath: '/module/crm'
      preLoaderRoute: typeof AuthenticatedAppModuleCrmRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/_app/module/cal': {
      id: '/_authenticated/_app/module/cal'
      path: '/module/cal'
      fullPath: '/module/cal'
      preLoaderRoute: typeof AuthenticatedAppModuleCalRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
  }
}

interface AuthenticatedAppRouteChildren {
  AuthenticatedAppProfileRoute: typeof AuthenticatedAppProfileRoute
  AuthenticatedAppIndexRoute: typeof AuthenticatedAppIndexRoute
  AuthenticatedAppModuleCalRoute: typeof AuthenticatedAppModuleCalRoute
  AuthenticatedAppModuleCrmRoute: typeof AuthenticatedAppModuleCrmRoute
  AuthenticatedAppModuleFilesRoute: typeof AuthenticatedAppModuleFilesRoute
  AuthenticatedAppModuleFinRoute: typeof AuthenticatedAppModuleFinRoute
  AuthenticatedAppModuleHealthRoute: typeof AuthenticatedAppModuleHealthRoute
  AuthenticatedAppModuleMailRoute: typeof AuthenticatedAppModuleMailRoute
  AuthenticatedAppModuleNotesRoute: typeof AuthenticatedAppModuleNotesRoute
  AuthenticatedAppModuleSocialRoute: typeof AuthenticatedAppModuleSocialRoute
  AuthenticatedAppModuleTaskRoute: typeof AuthenticatedAppModuleTaskRoute
  AuthenticatedAppModuleTravelRoute: typeof AuthenticatedAppModuleTravelRoute
}

const AuthenticatedAppRouteChildren: AuthenticatedAppRouteChildren = {
  AuthenticatedAppProfileRoute: AuthenticatedAppProfileRoute,
  AuthenticatedAppIndexRoute: AuthenticatedAppIndexRoute,
  AuthenticatedAppModuleCalRoute: AuthenticatedAppModuleCalRoute,
  AuthenticatedAppModuleCrmRoute: AuthenticatedAppModuleCrmRoute,
  AuthenticatedAppModuleFilesRoute: AuthenticatedAppModuleFilesRoute,
  AuthenticatedAppModuleFinRoute: AuthenticatedAppModuleFinRoute,
  AuthenticatedAppModuleHealthRoute: AuthenticatedAppModuleHealthRoute,
  AuthenticatedAppModuleMailRoute: AuthenticatedAppModuleMailRoute,
  AuthenticatedAppModuleNotesRoute: AuthenticatedAppModuleNotesRoute,
  AuthenticatedAppModuleSocialRoute: AuthenticatedAppModuleSocialRoute,
  AuthenticatedAppModuleTaskRoute: AuthenticatedAppModuleTaskRoute,
  AuthenticatedAppModuleTravelRoute: AuthenticatedAppModuleTravelRoute,
}

const AuthenticatedAppRouteWithChildren =
  AuthenticatedAppRoute._addFileChildren(AuthenticatedAppRouteChildren)

interface AuthenticatedOnboardingRouteChildren {
  AuthenticatedOnboardingLaunchRoute: typeof AuthenticatedOnboardingLaunchRoute
  AuthenticatedOnboardingStep1Route: typeof AuthenticatedOnboardingStep1Route
  AuthenticatedOnboardingStep2Route: typeof AuthenticatedOnboardingStep2Route
  AuthenticatedOnboardingStep3Route: typeof AuthenticatedOnboardingStep3Route
  AuthenticatedOnboardingStep4Route: typeof AuthenticatedOnboardingStep4Route
  AuthenticatedOnboardingIndexRoute: typeof AuthenticatedOnboardingIndexRoute
}

const AuthenticatedOnboardingRouteChildren: AuthenticatedOnboardingRouteChildren =
  {
    AuthenticatedOnboardingLaunchRoute: AuthenticatedOnboardingLaunchRoute,
    AuthenticatedOnboardingStep1Route: AuthenticatedOnboardingStep1Route,
    AuthenticatedOnboardingStep2Route: AuthenticatedOnboardingStep2Route,
    AuthenticatedOnboardingStep3Route: AuthenticatedOnboardingStep3Route,
    AuthenticatedOnboardingStep4Route: AuthenticatedOnboardingStep4Route,
    AuthenticatedOnboardingIndexRoute: AuthenticatedOnboardingIndexRoute,
  }

const AuthenticatedOnboardingRouteWithChildren =
  AuthenticatedOnboardingRoute._addFileChildren(
    AuthenticatedOnboardingRouteChildren,
  )

interface AuthenticatedRouteChildren {
  AuthenticatedAppRoute: typeof AuthenticatedAppRouteWithChildren
  AuthenticatedOnboardingRoute: typeof AuthenticatedOnboardingRouteWithChildren
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedAppRoute: AuthenticatedAppRouteWithChildren,
  AuthenticatedOnboardingRoute: AuthenticatedOnboardingRouteWithChildren,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  AuthRoute: AuthRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
