/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as AuthenticatedOnboardingRouteImport } from './routes/_authenticated/onboarding'
import { Route as AuthenticatedAppRouteImport } from './routes/_authenticated/_app'
import { Route as AuthenticatedOnboardingIndexRouteImport } from './routes/_authenticated/onboarding/index'
import { Route as AuthenticatedAppIndexRouteImport } from './routes/_authenticated/_app/index'
import { Route as AuthenticatedOnboardingStep4RouteImport } from './routes/_authenticated/onboarding/step4'
import { Route as AuthenticatedOnboardingStep3RouteImport } from './routes/_authenticated/onboarding/step3'
import { Route as AuthenticatedOnboardingStep2RouteImport } from './routes/_authenticated/onboarding/step2'
import { Route as AuthenticatedOnboardingStep1RouteImport } from './routes/_authenticated/onboarding/step1'
import { Route as AuthenticatedOnboardingLaunchRouteImport } from './routes/_authenticated/onboarding/launch'
import { Route as AuthenticatedAppProfileRouteImport } from './routes/_authenticated/_app/profile'
import { Route as AuthenticatedAppNotificationsRouteImport } from './routes/_authenticated/_app/notifications'
import { Route as AuthenticatedAppModuleTravelRouteImport } from './routes/_authenticated/_app/module/travel'
import { Route as AuthenticatedAppModuleTaskRouteImport } from './routes/_authenticated/_app/module/task'
import { Route as AuthenticatedAppModuleSocialRouteImport } from './routes/_authenticated/_app/module/social'
import { Route as AuthenticatedAppModuleNotesRouteImport } from './routes/_authenticated/_app/module/notes'
import { Route as AuthenticatedAppModuleMailRouteImport } from './routes/_authenticated/_app/module/mail'
import { Route as AuthenticatedAppModuleHealthRouteImport } from './routes/_authenticated/_app/module/health'
import { Route as AuthenticatedAppModuleFinRouteImport } from './routes/_authenticated/_app/module/fin'
import { Route as AuthenticatedAppModuleFilesRouteImport } from './routes/_authenticated/_app/module/files'
import { Route as AuthenticatedAppModuleCrmRouteImport } from './routes/_authenticated/_app/module/crm'
import { Route as AuthenticatedAppModuleCalRouteImport } from './routes/_authenticated/_app/module/cal'
import { Route as AuthenticatedAppModuleTaskIndexRouteImport } from './routes/_authenticated/_app/module/task/index'
import { Route as AuthenticatedAppModuleMailIndexRouteImport } from './routes/_authenticated/_app/module/mail/index'
import { Route as AuthenticatedAppModuleCrmIndexRouteImport } from './routes/_authenticated/_app/module/crm/index'
import { Route as AuthenticatedAppModuleCalIndexRouteImport } from './routes/_authenticated/_app/module/cal/index'
import { Route as AuthenticatedAppModuleCrmContactIdRouteImport } from './routes/_authenticated/_app/module/crm/$contactId'
import { Route as AuthenticatedAppModuleTaskListIndexRouteImport } from './routes/_authenticated/_app/module/task/list.index'
import { Route as AuthenticatedAppModuleTaskCalendarIndexRouteImport } from './routes/_authenticated/_app/module/task/calendar.index'
import { Route as AuthenticatedAppModuleMailSentIndexRouteImport } from './routes/_authenticated/_app/module/mail/sent.index'
import { Route as AuthenticatedAppModuleMailInboxIndexRouteImport } from './routes/_authenticated/_app/module/mail/inbox.index'
import { Route as AuthenticatedAppModuleMailDraftsIndexRouteImport } from './routes/_authenticated/_app/module/mail/drafts.index'
import { Route as AuthenticatedAppModuleMailAttachmentsIndexRouteImport } from './routes/_authenticated/_app/module/mail/attachments.index'
import { Route as AuthenticatedAppModuleCrmListIndexRouteImport } from './routes/_authenticated/_app/module/crm/list.index'
import { Route as AuthenticatedAppModuleCrmFollowUpsIndexRouteImport } from './routes/_authenticated/_app/module/crm/follow-ups.index'
import { Route as AuthenticatedAppModuleCalWeekIndexRouteImport } from './routes/_authenticated/_app/module/cal/week.index'
import { Route as AuthenticatedAppModuleCalMonthIndexRouteImport } from './routes/_authenticated/_app/module/cal/month.index'
import { Route as AuthenticatedAppModuleTaskProjectProjectIdRouteImport } from './routes/_authenticated/_app/module/task/project.$projectId'
import { Route as AuthenticatedAppModuleMailInboxEmailIdRouteImport } from './routes/_authenticated/_app/module/mail/inbox.$emailId'

const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedOnboardingRoute = AuthenticatedOnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedAppRoute = AuthenticatedAppRouteImport.update({
  id: '/_app',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedOnboardingIndexRoute =
  AuthenticatedOnboardingIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedOnboardingRoute,
  } as any)
const AuthenticatedAppIndexRoute = AuthenticatedAppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedAppRoute,
} as any)
const AuthenticatedOnboardingStep4Route =
  AuthenticatedOnboardingStep4RouteImport.update({
    id: '/step4',
    path: '/step4',
    getParentRoute: () => AuthenticatedOnboardingRoute,
  } as any)
const AuthenticatedOnboardingStep3Route =
  AuthenticatedOnboardingStep3RouteImport.update({
    id: '/step3',
    path: '/step3',
    getParentRoute: () => AuthenticatedOnboardingRoute,
  } as any)
const AuthenticatedOnboardingStep2Route =
  AuthenticatedOnboardingStep2RouteImport.update({
    id: '/step2',
    path: '/step2',
    getParentRoute: () => AuthenticatedOnboardingRoute,
  } as any)
const AuthenticatedOnboardingStep1Route =
  AuthenticatedOnboardingStep1RouteImport.update({
    id: '/step1',
    path: '/step1',
    getParentRoute: () => AuthenticatedOnboardingRoute,
  } as any)
const AuthenticatedOnboardingLaunchRoute =
  AuthenticatedOnboardingLaunchRouteImport.update({
    id: '/launch',
    path: '/launch',
    getParentRoute: () => AuthenticatedOnboardingRoute,
  } as any)
const AuthenticatedAppProfileRoute = AuthenticatedAppProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AuthenticatedAppRoute,
} as any)
const AuthenticatedAppNotificationsRoute =
  AuthenticatedAppNotificationsRouteImport.update({
    id: '/notifications',
    path: '/notifications',
    getParentRoute: () => AuthenticatedAppRoute,
  } as any)
const AuthenticatedAppModuleTravelRoute =
  AuthenticatedAppModuleTravelRouteImport.update({
    id: '/module/travel',
    path: '/module/travel',
    getParentRoute: () => AuthenticatedAppRoute,
  } as any)
const AuthenticatedAppModuleTaskRoute =
  AuthenticatedAppModuleTaskRouteImport.update({
    id: '/module/task',
    path: '/module/task',
    getParentRoute: () => AuthenticatedAppRoute,
  } as any)
const AuthenticatedAppModuleSocialRoute =
  AuthenticatedAppModuleSocialRouteImport.update({
    id: '/module/social',
    path: '/module/social',
    getParentRoute: () => AuthenticatedAppRoute,
  } as any)
const AuthenticatedAppModuleNotesRoute =
  AuthenticatedAppModuleNotesRouteImport.update({
    id: '/module/notes',
    path: '/module/notes',
    getParentRoute: () => AuthenticatedAppRoute,
  } as any)
const AuthenticatedAppModuleMailRoute =
  AuthenticatedAppModuleMailRouteImport.update({
    id: '/module/mail',
    path: '/module/mail',
    getParentRoute: () => AuthenticatedAppRoute,
  } as any)
const AuthenticatedAppModuleHealthRoute =
  AuthenticatedAppModuleHealthRouteImport.update({
    id: '/module/health',
    path: '/module/health',
    getParentRoute: () => AuthenticatedAppRoute,
  } as any)
const AuthenticatedAppModuleFinRoute =
  AuthenticatedAppModuleFinRouteImport.update({
    id: '/module/fin',
    path: '/module/fin',
    getParentRoute: () => AuthenticatedAppRoute,
  } as any)
const AuthenticatedAppModuleFilesRoute =
  AuthenticatedAppModuleFilesRouteImport.update({
    id: '/module/files',
    path: '/module/files',
    getParentRoute: () => AuthenticatedAppRoute,
  } as any)
const AuthenticatedAppModuleCrmRoute =
  AuthenticatedAppModuleCrmRouteImport.update({
    id: '/module/crm',
    path: '/module/crm',
    getParentRoute: () => AuthenticatedAppRoute,
  } as any)
const AuthenticatedAppModuleCalRoute =
  AuthenticatedAppModuleCalRouteImport.update({
    id: '/module/cal',
    path: '/module/cal',
    getParentRoute: () => AuthenticatedAppRoute,
  } as any)
const AuthenticatedAppModuleTaskIndexRoute =
  AuthenticatedAppModuleTaskIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedAppModuleTaskRoute,
  } as any)
const AuthenticatedAppModuleMailIndexRoute =
  AuthenticatedAppModuleMailIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedAppModuleMailRoute,
  } as any)
const AuthenticatedAppModuleCrmIndexRoute =
  AuthenticatedAppModuleCrmIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedAppModuleCrmRoute,
  } as any)
const AuthenticatedAppModuleCalIndexRoute =
  AuthenticatedAppModuleCalIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedAppModuleCalRoute,
  } as any)
const AuthenticatedAppModuleCrmContactIdRoute =
  AuthenticatedAppModuleCrmContactIdRouteImport.update({
    id: '/$contactId',
    path: '/$contactId',
    getParentRoute: () => AuthenticatedAppModuleCrmRoute,
  } as any)
const AuthenticatedAppModuleTaskListIndexRoute =
  AuthenticatedAppModuleTaskListIndexRouteImport.update({
    id: '/list/',
    path: '/list/',
    getParentRoute: () => AuthenticatedAppModuleTaskRoute,
  } as any)
const AuthenticatedAppModuleTaskCalendarIndexRoute =
  AuthenticatedAppModuleTaskCalendarIndexRouteImport.update({
    id: '/calendar/',
    path: '/calendar/',
    getParentRoute: () => AuthenticatedAppModuleTaskRoute,
  } as any)
const AuthenticatedAppModuleMailSentIndexRoute =
  AuthenticatedAppModuleMailSentIndexRouteImport.update({
    id: '/sent/',
    path: '/sent/',
    getParentRoute: () => AuthenticatedAppModuleMailRoute,
  } as any)
const AuthenticatedAppModuleMailInboxIndexRoute =
  AuthenticatedAppModuleMailInboxIndexRouteImport.update({
    id: '/inbox/',
    path: '/inbox/',
    getParentRoute: () => AuthenticatedAppModuleMailRoute,
  } as any)
const AuthenticatedAppModuleMailDraftsIndexRoute =
  AuthenticatedAppModuleMailDraftsIndexRouteImport.update({
    id: '/drafts/',
    path: '/drafts/',
    getParentRoute: () => AuthenticatedAppModuleMailRoute,
  } as any)
const AuthenticatedAppModuleMailAttachmentsIndexRoute =
  AuthenticatedAppModuleMailAttachmentsIndexRouteImport.update({
    id: '/attachments/',
    path: '/attachments/',
    getParentRoute: () => AuthenticatedAppModuleMailRoute,
  } as any)
const AuthenticatedAppModuleCrmListIndexRoute =
  AuthenticatedAppModuleCrmListIndexRouteImport.update({
    id: '/list/',
    path: '/list/',
    getParentRoute: () => AuthenticatedAppModuleCrmRoute,
  } as any)
const AuthenticatedAppModuleCrmFollowUpsIndexRoute =
  AuthenticatedAppModuleCrmFollowUpsIndexRouteImport.update({
    id: '/follow-ups/',
    path: '/follow-ups/',
    getParentRoute: () => AuthenticatedAppModuleCrmRoute,
  } as any)
const AuthenticatedAppModuleCalWeekIndexRoute =
  AuthenticatedAppModuleCalWeekIndexRouteImport.update({
    id: '/week/',
    path: '/week/',
    getParentRoute: () => AuthenticatedAppModuleCalRoute,
  } as any)
const AuthenticatedAppModuleCalMonthIndexRoute =
  AuthenticatedAppModuleCalMonthIndexRouteImport.update({
    id: '/month/',
    path: '/month/',
    getParentRoute: () => AuthenticatedAppModuleCalRoute,
  } as any)
const AuthenticatedAppModuleTaskProjectProjectIdRoute =
  AuthenticatedAppModuleTaskProjectProjectIdRouteImport.update({
    id: '/project/$projectId',
    path: '/project/$projectId',
    getParentRoute: () => AuthenticatedAppModuleTaskRoute,
  } as any)
const AuthenticatedAppModuleMailInboxEmailIdRoute =
  AuthenticatedAppModuleMailInboxEmailIdRouteImport.update({
    id: '/inbox/$emailId',
    path: '/inbox/$emailId',
    getParentRoute: () => AuthenticatedAppModuleMailRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof AuthenticatedAppIndexRoute
  '/auth': typeof AuthRoute
  '/onboarding': typeof AuthenticatedOnboardingRouteWithChildren
  '/notifications': typeof AuthenticatedAppNotificationsRoute
  '/profile': typeof AuthenticatedAppProfileRoute
  '/onboarding/launch': typeof AuthenticatedOnboardingLaunchRoute
  '/onboarding/step1': typeof AuthenticatedOnboardingStep1Route
  '/onboarding/step2': typeof AuthenticatedOnboardingStep2Route
  '/onboarding/step3': typeof AuthenticatedOnboardingStep3Route
  '/onboarding/step4': typeof AuthenticatedOnboardingStep4Route
  '/onboarding/': typeof AuthenticatedOnboardingIndexRoute
  '/module/cal': typeof AuthenticatedAppModuleCalRouteWithChildren
  '/module/crm': typeof AuthenticatedAppModuleCrmRouteWithChildren
  '/module/files': typeof AuthenticatedAppModuleFilesRoute
  '/module/fin': typeof AuthenticatedAppModuleFinRoute
  '/module/health': typeof AuthenticatedAppModuleHealthRoute
  '/module/mail': typeof AuthenticatedAppModuleMailRouteWithChildren
  '/module/notes': typeof AuthenticatedAppModuleNotesRoute
  '/module/social': typeof AuthenticatedAppModuleSocialRoute
  '/module/task': typeof AuthenticatedAppModuleTaskRouteWithChildren
  '/module/travel': typeof AuthenticatedAppModuleTravelRoute
  '/module/crm/$contactId': typeof AuthenticatedAppModuleCrmContactIdRoute
  '/module/cal/': typeof AuthenticatedAppModuleCalIndexRoute
  '/module/crm/': typeof AuthenticatedAppModuleCrmIndexRoute
  '/module/mail/': typeof AuthenticatedAppModuleMailIndexRoute
  '/module/task/': typeof AuthenticatedAppModuleTaskIndexRoute
  '/module/mail/inbox/$emailId': typeof AuthenticatedAppModuleMailInboxEmailIdRoute
  '/module/task/project/$projectId': typeof AuthenticatedAppModuleTaskProjectProjectIdRoute
  '/module/cal/month/': typeof AuthenticatedAppModuleCalMonthIndexRoute
  '/module/cal/week/': typeof AuthenticatedAppModuleCalWeekIndexRoute
  '/module/crm/follow-ups/': typeof AuthenticatedAppModuleCrmFollowUpsIndexRoute
  '/module/crm/list/': typeof AuthenticatedAppModuleCrmListIndexRoute
  '/module/mail/attachments/': typeof AuthenticatedAppModuleMailAttachmentsIndexRoute
  '/module/mail/drafts/': typeof AuthenticatedAppModuleMailDraftsIndexRoute
  '/module/mail/inbox/': typeof AuthenticatedAppModuleMailInboxIndexRoute
  '/module/mail/sent/': typeof AuthenticatedAppModuleMailSentIndexRoute
  '/module/task/calendar/': typeof AuthenticatedAppModuleTaskCalendarIndexRoute
  '/module/task/list/': typeof AuthenticatedAppModuleTaskListIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof AuthenticatedAppIndexRoute
  '/auth': typeof AuthRoute
  '/notifications': typeof AuthenticatedAppNotificationsRoute
  '/profile': typeof AuthenticatedAppProfileRoute
  '/onboarding/launch': typeof AuthenticatedOnboardingLaunchRoute
  '/onboarding/step1': typeof AuthenticatedOnboardingStep1Route
  '/onboarding/step2': typeof AuthenticatedOnboardingStep2Route
  '/onboarding/step3': typeof AuthenticatedOnboardingStep3Route
  '/onboarding/step4': typeof AuthenticatedOnboardingStep4Route
  '/onboarding': typeof AuthenticatedOnboardingIndexRoute
  '/module/files': typeof AuthenticatedAppModuleFilesRoute
  '/module/fin': typeof AuthenticatedAppModuleFinRoute
  '/module/health': typeof AuthenticatedAppModuleHealthRoute
  '/module/notes': typeof AuthenticatedAppModuleNotesRoute
  '/module/social': typeof AuthenticatedAppModuleSocialRoute
  '/module/travel': typeof AuthenticatedAppModuleTravelRoute
  '/module/crm/$contactId': typeof AuthenticatedAppModuleCrmContactIdRoute
  '/module/cal': typeof AuthenticatedAppModuleCalIndexRoute
  '/module/crm': typeof AuthenticatedAppModuleCrmIndexRoute
  '/module/mail': typeof AuthenticatedAppModuleMailIndexRoute
  '/module/task': typeof AuthenticatedAppModuleTaskIndexRoute
  '/module/mail/inbox/$emailId': typeof AuthenticatedAppModuleMailInboxEmailIdRoute
  '/module/task/project/$projectId': typeof AuthenticatedAppModuleTaskProjectProjectIdRoute
  '/module/cal/month': typeof AuthenticatedAppModuleCalMonthIndexRoute
  '/module/cal/week': typeof AuthenticatedAppModuleCalWeekIndexRoute
  '/module/crm/follow-ups': typeof AuthenticatedAppModuleCrmFollowUpsIndexRoute
  '/module/crm/list': typeof AuthenticatedAppModuleCrmListIndexRoute
  '/module/mail/attachments': typeof AuthenticatedAppModuleMailAttachmentsIndexRoute
  '/module/mail/drafts': typeof AuthenticatedAppModuleMailDraftsIndexRoute
  '/module/mail/inbox': typeof AuthenticatedAppModuleMailInboxIndexRoute
  '/module/mail/sent': typeof AuthenticatedAppModuleMailSentIndexRoute
  '/module/task/calendar': typeof AuthenticatedAppModuleTaskCalendarIndexRoute
  '/module/task/list': typeof AuthenticatedAppModuleTaskListIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/auth': typeof AuthRoute
  '/_authenticated/_app': typeof AuthenticatedAppRouteWithChildren
  '/_authenticated/onboarding': typeof AuthenticatedOnboardingRouteWithChildren
  '/_authenticated/_app/notifications': typeof AuthenticatedAppNotificationsRoute
  '/_authenticated/_app/profile': typeof AuthenticatedAppProfileRoute
  '/_authenticated/onboarding/launch': typeof AuthenticatedOnboardingLaunchRoute
  '/_authenticated/onboarding/step1': typeof AuthenticatedOnboardingStep1Route
  '/_authenticated/onboarding/step2': typeof AuthenticatedOnboardingStep2Route
  '/_authenticated/onboarding/step3': typeof AuthenticatedOnboardingStep3Route
  '/_authenticated/onboarding/step4': typeof AuthenticatedOnboardingStep4Route
  '/_authenticated/_app/': typeof AuthenticatedAppIndexRoute
  '/_authenticated/onboarding/': typeof AuthenticatedOnboardingIndexRoute
  '/_authenticated/_app/module/cal': typeof AuthenticatedAppModuleCalRouteWithChildren
  '/_authenticated/_app/module/crm': typeof AuthenticatedAppModuleCrmRouteWithChildren
  '/_authenticated/_app/module/files': typeof AuthenticatedAppModuleFilesRoute
  '/_authenticated/_app/module/fin': typeof AuthenticatedAppModuleFinRoute
  '/_authenticated/_app/module/health': typeof AuthenticatedAppModuleHealthRoute
  '/_authenticated/_app/module/mail': typeof AuthenticatedAppModuleMailRouteWithChildren
  '/_authenticated/_app/module/notes': typeof AuthenticatedAppModuleNotesRoute
  '/_authenticated/_app/module/social': typeof AuthenticatedAppModuleSocialRoute
  '/_authenticated/_app/module/task': typeof AuthenticatedAppModuleTaskRouteWithChildren
  '/_authenticated/_app/module/travel': typeof AuthenticatedAppModuleTravelRoute
  '/_authenticated/_app/module/crm/$contactId': typeof AuthenticatedAppModuleCrmContactIdRoute
  '/_authenticated/_app/module/cal/': typeof AuthenticatedAppModuleCalIndexRoute
  '/_authenticated/_app/module/crm/': typeof AuthenticatedAppModuleCrmIndexRoute
  '/_authenticated/_app/module/mail/': typeof AuthenticatedAppModuleMailIndexRoute
  '/_authenticated/_app/module/task/': typeof AuthenticatedAppModuleTaskIndexRoute
  '/_authenticated/_app/module/mail/inbox/$emailId': typeof AuthenticatedAppModuleMailInboxEmailIdRoute
  '/_authenticated/_app/module/task/project/$projectId': typeof AuthenticatedAppModuleTaskProjectProjectIdRoute
  '/_authenticated/_app/module/cal/month/': typeof AuthenticatedAppModuleCalMonthIndexRoute
  '/_authenticated/_app/module/cal/week/': typeof AuthenticatedAppModuleCalWeekIndexRoute
  '/_authenticated/_app/module/crm/follow-ups/': typeof AuthenticatedAppModuleCrmFollowUpsIndexRoute
  '/_authenticated/_app/module/crm/list/': typeof AuthenticatedAppModuleCrmListIndexRoute
  '/_authenticated/_app/module/mail/attachments/': typeof AuthenticatedAppModuleMailAttachmentsIndexRoute
  '/_authenticated/_app/module/mail/drafts/': typeof AuthenticatedAppModuleMailDraftsIndexRoute
  '/_authenticated/_app/module/mail/inbox/': typeof AuthenticatedAppModuleMailInboxIndexRoute
  '/_authenticated/_app/module/mail/sent/': typeof AuthenticatedAppModuleMailSentIndexRoute
  '/_authenticated/_app/module/task/calendar/': typeof AuthenticatedAppModuleTaskCalendarIndexRoute
  '/_authenticated/_app/module/task/list/': typeof AuthenticatedAppModuleTaskListIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/onboarding'
    | '/notifications'
    | '/profile'
    | '/onboarding/launch'
    | '/onboarding/step1'
    | '/onboarding/step2'
    | '/onboarding/step3'
    | '/onboarding/step4'
    | '/onboarding/'
    | '/module/cal'
    | '/module/crm'
    | '/module/files'
    | '/module/fin'
    | '/module/health'
    | '/module/mail'
    | '/module/notes'
    | '/module/social'
    | '/module/task'
    | '/module/travel'
    | '/module/crm/$contactId'
    | '/module/cal/'
    | '/module/crm/'
    | '/module/mail/'
    | '/module/task/'
    | '/module/mail/inbox/$emailId'
    | '/module/task/project/$projectId'
    | '/module/cal/month/'
    | '/module/cal/week/'
    | '/module/crm/follow-ups/'
    | '/module/crm/list/'
    | '/module/mail/attachments/'
    | '/module/mail/drafts/'
    | '/module/mail/inbox/'
    | '/module/mail/sent/'
    | '/module/task/calendar/'
    | '/module/task/list/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/notifications'
    | '/profile'
    | '/onboarding/launch'
    | '/onboarding/step1'
    | '/onboarding/step2'
    | '/onboarding/step3'
    | '/onboarding/step4'
    | '/onboarding'
    | '/module/files'
    | '/module/fin'
    | '/module/health'
    | '/module/notes'
    | '/module/social'
    | '/module/travel'
    | '/module/crm/$contactId'
    | '/module/cal'
    | '/module/crm'
    | '/module/mail'
    | '/module/task'
    | '/module/mail/inbox/$emailId'
    | '/module/task/project/$projectId'
    | '/module/cal/month'
    | '/module/cal/week'
    | '/module/crm/follow-ups'
    | '/module/crm/list'
    | '/module/mail/attachments'
    | '/module/mail/drafts'
    | '/module/mail/inbox'
    | '/module/mail/sent'
    | '/module/task/calendar'
    | '/module/task/list'
  id:
    | '__root__'
    | '/_authenticated'
    | '/auth'
    | '/_authenticated/_app'
    | '/_authenticated/onboarding'
    | '/_authenticated/_app/notifications'
    | '/_authenticated/_app/profile'
    | '/_authenticated/onboarding/launch'
    | '/_authenticated/onboarding/step1'
    | '/_authenticated/onboarding/step2'
    | '/_authenticated/onboarding/step3'
    | '/_authenticated/onboarding/step4'
    | '/_authenticated/_app/'
    | '/_authenticated/onboarding/'
    | '/_authenticated/_app/module/cal'
    | '/_authenticated/_app/module/crm'
    | '/_authenticated/_app/module/files'
    | '/_authenticated/_app/module/fin'
    | '/_authenticated/_app/module/health'
    | '/_authenticated/_app/module/mail'
    | '/_authenticated/_app/module/notes'
    | '/_authenticated/_app/module/social'
    | '/_authenticated/_app/module/task'
    | '/_authenticated/_app/module/travel'
    | '/_authenticated/_app/module/crm/$contactId'
    | '/_authenticated/_app/module/cal/'
    | '/_authenticated/_app/module/crm/'
    | '/_authenticated/_app/module/mail/'
    | '/_authenticated/_app/module/task/'
    | '/_authenticated/_app/module/mail/inbox/$emailId'
    | '/_authenticated/_app/module/task/project/$projectId'
    | '/_authenticated/_app/module/cal/month/'
    | '/_authenticated/_app/module/cal/week/'
    | '/_authenticated/_app/module/crm/follow-ups/'
    | '/_authenticated/_app/module/crm/list/'
    | '/_authenticated/_app/module/mail/attachments/'
    | '/_authenticated/_app/module/mail/drafts/'
    | '/_authenticated/_app/module/mail/inbox/'
    | '/_authenticated/_app/module/mail/sent/'
    | '/_authenticated/_app/module/task/calendar/'
    | '/_authenticated/_app/module/task/list/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  AuthRoute: typeof AuthRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/onboarding': {
      id: '/_authenticated/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof AuthenticatedOnboardingRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/_app': {
      id: '/_authenticated/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedAppRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/onboarding/': {
      id: '/_authenticated/onboarding/'
      path: '/'
      fullPath: '/onboarding/'
      preLoaderRoute: typeof AuthenticatedOnboardingIndexRouteImport
      parentRoute: typeof AuthenticatedOnboardingRoute
    }
    '/_authenticated/_app/': {
      id: '/_authenticated/_app/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedAppIndexRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/onboarding/step4': {
      id: '/_authenticated/onboarding/step4'
      path: '/step4'
      fullPath: '/onboarding/step4'
      preLoaderRoute: typeof AuthenticatedOnboardingStep4RouteImport
      parentRoute: typeof AuthenticatedOnboardingRoute
    }
    '/_authenticated/onboarding/step3': {
      id: '/_authenticated/onboarding/step3'
      path: '/step3'
      fullPath: '/onboarding/step3'
      preLoaderRoute: typeof AuthenticatedOnboardingStep3RouteImport
      parentRoute: typeof AuthenticatedOnboardingRoute
    }
    '/_authenticated/onboarding/step2': {
      id: '/_authenticated/onboarding/step2'
      path: '/step2'
      fullPath: '/onboarding/step2'
      preLoaderRoute: typeof AuthenticatedOnboardingStep2RouteImport
      parentRoute: typeof AuthenticatedOnboardingRoute
    }
    '/_authenticated/onboarding/step1': {
      id: '/_authenticated/onboarding/step1'
      path: '/step1'
      fullPath: '/onboarding/step1'
      preLoaderRoute: typeof AuthenticatedOnboardingStep1RouteImport
      parentRoute: typeof AuthenticatedOnboardingRoute
    }
    '/_authenticated/onboarding/launch': {
      id: '/_authenticated/onboarding/launch'
      path: '/launch'
      fullPath: '/onboarding/launch'
      preLoaderRoute: typeof AuthenticatedOnboardingLaunchRouteImport
      parentRoute: typeof AuthenticatedOnboardingRoute
    }
    '/_authenticated/_app/profile': {
      id: '/_authenticated/_app/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof AuthenticatedAppProfileRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/_app/notifications': {
      id: '/_authenticated/_app/notifications'
      path: '/notifications'
      fullPath: '/notifications'
      preLoaderRoute: typeof AuthenticatedAppNotificationsRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/_app/module/travel': {
      id: '/_authenticated/_app/module/travel'
      path: '/module/travel'
      fullPath: '/module/travel'
      preLoaderRoute: typeof AuthenticatedAppModuleTravelRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/_app/module/task': {
      id: '/_authenticated/_app/module/task'
      path: '/module/task'
      fullPath: '/module/task'
      preLoaderRoute: typeof AuthenticatedAppModuleTaskRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/_app/module/social': {
      id: '/_authenticated/_app/module/social'
      path: '/module/social'
      fullPath: '/module/social'
      preLoaderRoute: typeof AuthenticatedAppModuleSocialRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/_app/module/notes': {
      id: '/_authenticated/_app/module/notes'
      path: '/module/notes'
      fullPath: '/module/notes'
      preLoaderRoute: typeof AuthenticatedAppModuleNotesRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/_app/module/mail': {
      id: '/_authenticated/_app/module/mail'
      path: '/module/mail'
      fullPath: '/module/mail'
      preLoaderRoute: typeof AuthenticatedAppModuleMailRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/_app/module/health': {
      id: '/_authenticated/_app/module/health'
      path: '/module/health'
      fullPath: '/module/health'
      preLoaderRoute: typeof AuthenticatedAppModuleHealthRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/_app/module/fin': {
      id: '/_authenticated/_app/module/fin'
      path: '/module/fin'
      fullPath: '/module/fin'
      preLoaderRoute: typeof AuthenticatedAppModuleFinRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/_app/module/files': {
      id: '/_authenticated/_app/module/files'
      path: '/module/files'
      fullPath: '/module/files'
      preLoaderRoute: typeof AuthenticatedAppModuleFilesRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/_app/module/crm': {
      id: '/_authenticated/_app/module/crm'
      path: '/module/crm'
      fullPath: '/module/crm'
      preLoaderRoute: typeof AuthenticatedAppModuleCrmRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/_app/module/cal': {
      id: '/_authenticated/_app/module/cal'
      path: '/module/cal'
      fullPath: '/module/cal'
      preLoaderRoute: typeof AuthenticatedAppModuleCalRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/_app/module/task/': {
      id: '/_authenticated/_app/module/task/'
      path: '/'
      fullPath: '/module/task/'
      preLoaderRoute: typeof AuthenticatedAppModuleTaskIndexRouteImport
      parentRoute: typeof AuthenticatedAppModuleTaskRoute
    }
    '/_authenticated/_app/module/mail/': {
      id: '/_authenticated/_app/module/mail/'
      path: '/'
      fullPath: '/module/mail/'
      preLoaderRoute: typeof AuthenticatedAppModuleMailIndexRouteImport
      parentRoute: typeof AuthenticatedAppModuleMailRoute
    }
    '/_authenticated/_app/module/crm/': {
      id: '/_authenticated/_app/module/crm/'
      path: '/'
      fullPath: '/module/crm/'
      preLoaderRoute: typeof AuthenticatedAppModuleCrmIndexRouteImport
      parentRoute: typeof AuthenticatedAppModuleCrmRoute
    }
    '/_authenticated/_app/module/cal/': {
      id: '/_authenticated/_app/module/cal/'
      path: '/'
      fullPath: '/module/cal/'
      preLoaderRoute: typeof AuthenticatedAppModuleCalIndexRouteImport
      parentRoute: typeof AuthenticatedAppModuleCalRoute
    }
    '/_authenticated/_app/module/crm/$contactId': {
      id: '/_authenticated/_app/module/crm/$contactId'
      path: '/$contactId'
      fullPath: '/module/crm/$contactId'
      preLoaderRoute: typeof AuthenticatedAppModuleCrmContactIdRouteImport
      parentRoute: typeof AuthenticatedAppModuleCrmRoute
    }
    '/_authenticated/_app/module/task/list/': {
      id: '/_authenticated/_app/module/task/list/'
      path: '/list'
      fullPath: '/module/task/list/'
      preLoaderRoute: typeof AuthenticatedAppModuleTaskListIndexRouteImport
      parentRoute: typeof AuthenticatedAppModuleTaskRoute
    }
    '/_authenticated/_app/module/task/calendar/': {
      id: '/_authenticated/_app/module/task/calendar/'
      path: '/calendar'
      fullPath: '/module/task/calendar/'
      preLoaderRoute: typeof AuthenticatedAppModuleTaskCalendarIndexRouteImport
      parentRoute: typeof AuthenticatedAppModuleTaskRoute
    }
    '/_authenticated/_app/module/mail/sent/': {
      id: '/_authenticated/_app/module/mail/sent/'
      path: '/sent'
      fullPath: '/module/mail/sent/'
      preLoaderRoute: typeof AuthenticatedAppModuleMailSentIndexRouteImport
      parentRoute: typeof AuthenticatedAppModuleMailRoute
    }
    '/_authenticated/_app/module/mail/inbox/': {
      id: '/_authenticated/_app/module/mail/inbox/'
      path: '/inbox'
      fullPath: '/module/mail/inbox/'
      preLoaderRoute: typeof AuthenticatedAppModuleMailInboxIndexRouteImport
      parentRoute: typeof AuthenticatedAppModuleMailRoute
    }
    '/_authenticated/_app/module/mail/drafts/': {
      id: '/_authenticated/_app/module/mail/drafts/'
      path: '/drafts'
      fullPath: '/module/mail/drafts/'
      preLoaderRoute: typeof AuthenticatedAppModuleMailDraftsIndexRouteImport
      parentRoute: typeof AuthenticatedAppModuleMailRoute
    }
    '/_authenticated/_app/module/mail/attachments/': {
      id: '/_authenticated/_app/module/mail/attachments/'
      path: '/attachments'
      fullPath: '/module/mail/attachments/'
      preLoaderRoute: typeof AuthenticatedAppModuleMailAttachmentsIndexRouteImport
      parentRoute: typeof AuthenticatedAppModuleMailRoute
    }
    '/_authenticated/_app/module/crm/list/': {
      id: '/_authenticated/_app/module/crm/list/'
      path: '/list'
      fullPath: '/module/crm/list/'
      preLoaderRoute: typeof AuthenticatedAppModuleCrmListIndexRouteImport
      parentRoute: typeof AuthenticatedAppModuleCrmRoute
    }
    '/_authenticated/_app/module/crm/follow-ups/': {
      id: '/_authenticated/_app/module/crm/follow-ups/'
      path: '/follow-ups'
      fullPath: '/module/crm/follow-ups/'
      preLoaderRoute: typeof AuthenticatedAppModuleCrmFollowUpsIndexRouteImport
      parentRoute: typeof AuthenticatedAppModuleCrmRoute
    }
    '/_authenticated/_app/module/cal/week/': {
      id: '/_authenticated/_app/module/cal/week/'
      path: '/week'
      fullPath: '/module/cal/week/'
      preLoaderRoute: typeof AuthenticatedAppModuleCalWeekIndexRouteImport
      parentRoute: typeof AuthenticatedAppModuleCalRoute
    }
    '/_authenticated/_app/module/cal/month/': {
      id: '/_authenticated/_app/module/cal/month/'
      path: '/month'
      fullPath: '/module/cal/month/'
      preLoaderRoute: typeof AuthenticatedAppModuleCalMonthIndexRouteImport
      parentRoute: typeof AuthenticatedAppModuleCalRoute
    }
    '/_authenticated/_app/module/task/project/$projectId': {
      id: '/_authenticated/_app/module/task/project/$projectId'
      path: '/project/$projectId'
      fullPath: '/module/task/project/$projectId'
      preLoaderRoute: typeof AuthenticatedAppModuleTaskProjectProjectIdRouteImport
      parentRoute: typeof AuthenticatedAppModuleTaskRoute
    }
    '/_authenticated/_app/module/mail/inbox/$emailId': {
      id: '/_authenticated/_app/module/mail/inbox/$emailId'
      path: '/inbox/$emailId'
      fullPath: '/module/mail/inbox/$emailId'
      preLoaderRoute: typeof AuthenticatedAppModuleMailInboxEmailIdRouteImport
      parentRoute: typeof AuthenticatedAppModuleMailRoute
    }
  }
}

interface AuthenticatedAppModuleCalRouteChildren {
  AuthenticatedAppModuleCalIndexRoute: typeof AuthenticatedAppModuleCalIndexRoute
  AuthenticatedAppModuleCalMonthIndexRoute: typeof AuthenticatedAppModuleCalMonthIndexRoute
  AuthenticatedAppModuleCalWeekIndexRoute: typeof AuthenticatedAppModuleCalWeekIndexRoute
}

const AuthenticatedAppModuleCalRouteChildren: AuthenticatedAppModuleCalRouteChildren =
  {
    AuthenticatedAppModuleCalIndexRoute: AuthenticatedAppModuleCalIndexRoute,
    AuthenticatedAppModuleCalMonthIndexRoute:
      AuthenticatedAppModuleCalMonthIndexRoute,
    AuthenticatedAppModuleCalWeekIndexRoute:
      AuthenticatedAppModuleCalWeekIndexRoute,
  }

const AuthenticatedAppModuleCalRouteWithChildren =
  AuthenticatedAppModuleCalRoute._addFileChildren(
    AuthenticatedAppModuleCalRouteChildren,
  )

interface AuthenticatedAppModuleCrmRouteChildren {
  AuthenticatedAppModuleCrmContactIdRoute: typeof AuthenticatedAppModuleCrmContactIdRoute
  AuthenticatedAppModuleCrmIndexRoute: typeof AuthenticatedAppModuleCrmIndexRoute
  AuthenticatedAppModuleCrmFollowUpsIndexRoute: typeof AuthenticatedAppModuleCrmFollowUpsIndexRoute
  AuthenticatedAppModuleCrmListIndexRoute: typeof AuthenticatedAppModuleCrmListIndexRoute
}

const AuthenticatedAppModuleCrmRouteChildren: AuthenticatedAppModuleCrmRouteChildren =
  {
    AuthenticatedAppModuleCrmContactIdRoute:
      AuthenticatedAppModuleCrmContactIdRoute,
    AuthenticatedAppModuleCrmIndexRoute: AuthenticatedAppModuleCrmIndexRoute,
    AuthenticatedAppModuleCrmFollowUpsIndexRoute:
      AuthenticatedAppModuleCrmFollowUpsIndexRoute,
    AuthenticatedAppModuleCrmListIndexRoute:
      AuthenticatedAppModuleCrmListIndexRoute,
  }

const AuthenticatedAppModuleCrmRouteWithChildren =
  AuthenticatedAppModuleCrmRoute._addFileChildren(
    AuthenticatedAppModuleCrmRouteChildren,
  )

interface AuthenticatedAppModuleMailRouteChildren {
  AuthenticatedAppModuleMailIndexRoute: typeof AuthenticatedAppModuleMailIndexRoute
  AuthenticatedAppModuleMailInboxEmailIdRoute: typeof AuthenticatedAppModuleMailInboxEmailIdRoute
  AuthenticatedAppModuleMailAttachmentsIndexRoute: typeof AuthenticatedAppModuleMailAttachmentsIndexRoute
  AuthenticatedAppModuleMailDraftsIndexRoute: typeof AuthenticatedAppModuleMailDraftsIndexRoute
  AuthenticatedAppModuleMailInboxIndexRoute: typeof AuthenticatedAppModuleMailInboxIndexRoute
  AuthenticatedAppModuleMailSentIndexRoute: typeof AuthenticatedAppModuleMailSentIndexRoute
}

const AuthenticatedAppModuleMailRouteChildren: AuthenticatedAppModuleMailRouteChildren =
  {
    AuthenticatedAppModuleMailIndexRoute: AuthenticatedAppModuleMailIndexRoute,
    AuthenticatedAppModuleMailInboxEmailIdRoute:
      AuthenticatedAppModuleMailInboxEmailIdRoute,
    AuthenticatedAppModuleMailAttachmentsIndexRoute:
      AuthenticatedAppModuleMailAttachmentsIndexRoute,
    AuthenticatedAppModuleMailDraftsIndexRoute:
      AuthenticatedAppModuleMailDraftsIndexRoute,
    AuthenticatedAppModuleMailInboxIndexRoute:
      AuthenticatedAppModuleMailInboxIndexRoute,
    AuthenticatedAppModuleMailSentIndexRoute:
      AuthenticatedAppModuleMailSentIndexRoute,
  }

const AuthenticatedAppModuleMailRouteWithChildren =
  AuthenticatedAppModuleMailRoute._addFileChildren(
    AuthenticatedAppModuleMailRouteChildren,
  )

interface AuthenticatedAppModuleTaskRouteChildren {
  AuthenticatedAppModuleTaskIndexRoute: typeof AuthenticatedAppModuleTaskIndexRoute
  AuthenticatedAppModuleTaskProjectProjectIdRoute: typeof AuthenticatedAppModuleTaskProjectProjectIdRoute
  AuthenticatedAppModuleTaskCalendarIndexRoute: typeof AuthenticatedAppModuleTaskCalendarIndexRoute
  AuthenticatedAppModuleTaskListIndexRoute: typeof AuthenticatedAppModuleTaskListIndexRoute
}

const AuthenticatedAppModuleTaskRouteChildren: AuthenticatedAppModuleTaskRouteChildren =
  {
    AuthenticatedAppModuleTaskIndexRoute: AuthenticatedAppModuleTaskIndexRoute,
    AuthenticatedAppModuleTaskProjectProjectIdRoute:
      AuthenticatedAppModuleTaskProjectProjectIdRoute,
    AuthenticatedAppModuleTaskCalendarIndexRoute:
      AuthenticatedAppModuleTaskCalendarIndexRoute,
    AuthenticatedAppModuleTaskListIndexRoute:
      AuthenticatedAppModuleTaskListIndexRoute,
  }

const AuthenticatedAppModuleTaskRouteWithChildren =
  AuthenticatedAppModuleTaskRoute._addFileChildren(
    AuthenticatedAppModuleTaskRouteChildren,
  )

interface AuthenticatedAppRouteChildren {
  AuthenticatedAppNotificationsRoute: typeof AuthenticatedAppNotificationsRoute
  AuthenticatedAppProfileRoute: typeof AuthenticatedAppProfileRoute
  AuthenticatedAppIndexRoute: typeof AuthenticatedAppIndexRoute
  AuthenticatedAppModuleCalRoute: typeof AuthenticatedAppModuleCalRouteWithChildren
  AuthenticatedAppModuleCrmRoute: typeof AuthenticatedAppModuleCrmRouteWithChildren
  AuthenticatedAppModuleFilesRoute: typeof AuthenticatedAppModuleFilesRoute
  AuthenticatedAppModuleFinRoute: typeof AuthenticatedAppModuleFinRoute
  AuthenticatedAppModuleHealthRoute: typeof AuthenticatedAppModuleHealthRoute
  AuthenticatedAppModuleMailRoute: typeof AuthenticatedAppModuleMailRouteWithChildren
  AuthenticatedAppModuleNotesRoute: typeof AuthenticatedAppModuleNotesRoute
  AuthenticatedAppModuleSocialRoute: typeof AuthenticatedAppModuleSocialRoute
  AuthenticatedAppModuleTaskRoute: typeof AuthenticatedAppModuleTaskRouteWithChildren
  AuthenticatedAppModuleTravelRoute: typeof AuthenticatedAppModuleTravelRoute
}

const AuthenticatedAppRouteChildren: AuthenticatedAppRouteChildren = {
  AuthenticatedAppNotificationsRoute: AuthenticatedAppNotificationsRoute,
  AuthenticatedAppProfileRoute: AuthenticatedAppProfileRoute,
  AuthenticatedAppIndexRoute: AuthenticatedAppIndexRoute,
  AuthenticatedAppModuleCalRoute: AuthenticatedAppModuleCalRouteWithChildren,
  AuthenticatedAppModuleCrmRoute: AuthenticatedAppModuleCrmRouteWithChildren,
  AuthenticatedAppModuleFilesRoute: AuthenticatedAppModuleFilesRoute,
  AuthenticatedAppModuleFinRoute: AuthenticatedAppModuleFinRoute,
  AuthenticatedAppModuleHealthRoute: AuthenticatedAppModuleHealthRoute,
  AuthenticatedAppModuleMailRoute: AuthenticatedAppModuleMailRouteWithChildren,
  AuthenticatedAppModuleNotesRoute: AuthenticatedAppModuleNotesRoute,
  AuthenticatedAppModuleSocialRoute: AuthenticatedAppModuleSocialRoute,
  AuthenticatedAppModuleTaskRoute: AuthenticatedAppModuleTaskRouteWithChildren,
  AuthenticatedAppModuleTravelRoute: AuthenticatedAppModuleTravelRoute,
}

const AuthenticatedAppRouteWithChildren =
  AuthenticatedAppRoute._addFileChildren(AuthenticatedAppRouteChildren)

interface AuthenticatedOnboardingRouteChildren {
  AuthenticatedOnboardingLaunchRoute: typeof AuthenticatedOnboardingLaunchRoute
  AuthenticatedOnboardingStep1Route: typeof AuthenticatedOnboardingStep1Route
  AuthenticatedOnboardingStep2Route: typeof AuthenticatedOnboardingStep2Route
  AuthenticatedOnboardingStep3Route: typeof AuthenticatedOnboardingStep3Route
  AuthenticatedOnboardingStep4Route: typeof AuthenticatedOnboardingStep4Route
  AuthenticatedOnboardingIndexRoute: typeof AuthenticatedOnboardingIndexRoute
}

const AuthenticatedOnboardingRouteChildren: AuthenticatedOnboardingRouteChildren =
  {
    AuthenticatedOnboardingLaunchRoute: AuthenticatedOnboardingLaunchRoute,
    AuthenticatedOnboardingStep1Route: AuthenticatedOnboardingStep1Route,
    AuthenticatedOnboardingStep2Route: AuthenticatedOnboardingStep2Route,
    AuthenticatedOnboardingStep3Route: AuthenticatedOnboardingStep3Route,
    AuthenticatedOnboardingStep4Route: AuthenticatedOnboardingStep4Route,
    AuthenticatedOnboardingIndexRoute: AuthenticatedOnboardingIndexRoute,
  }

const AuthenticatedOnboardingRouteWithChildren =
  AuthenticatedOnboardingRoute._addFileChildren(
    AuthenticatedOnboardingRouteChildren,
  )

interface AuthenticatedRouteChildren {
  AuthenticatedAppRoute: typeof AuthenticatedAppRouteWithChildren
  AuthenticatedOnboardingRoute: typeof AuthenticatedOnboardingRouteWithChildren
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedAppRoute: AuthenticatedAppRouteWithChildren,
  AuthenticatedOnboardingRoute: AuthenticatedOnboardingRouteWithChildren,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  AuthRoute: AuthRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
